### ISSUE TITLE
Works with ShuttlePro v1

### ISSUE THREAD

**Issue by smcnally** [abourget/shuttle-go#3]
Thank you for this code. Solely FYI: 

shuttle-go also works with the original ShuttlePro. Swap the v2 device name with v1's:

`/dev/input/by-id/usb-Contour_Design_ShuttlePRO-event-if00`

and your code works as designed.

I'm working on keybindings for Blender.  By default `sample_config.json` handles Video Sequencer timeline Zoom In (JogL) and Zoom Out (JogR) and transport start / stop (B4). 

Happy to have the Shuttle back in the mix. Many thanks.

**Comment by abourget** [comment]
If you want to provide sample configs for Blender, feel free to PR it here.

Is there any way the v1 could be added to the code, so that it auto-detects? Are you disposed to contribute this? :) that would be awesome :)

**Comment by smcnally** [comment]
I'll update config and submit a PR, thank you, and I'll look into
auto-detect,
will also update my GH notifications filter so I don't miss replies --
pardon my lag.

**Comment by smcnally** [comment]
I've shared PRs for `shuttle-pro-v1` and `blender-sample-config` 
The latter *should* work with v1 and v2. 
The former includes updates to your README with ShuttlePRO_v1-specifics.

Many thanks -

**Comment by notgernot** [comment]
where can i find or download the shuttle-pro-v1 files ?

**Comment by abourget** [comment]
hey thanks! just merged the PRs.. @notgernot not sure what you mean by Shuttle Pro v1 files.  The release should work on both as per @smcnally 's comments.. Check the "Releases" section.
Closing here, thanks Steve!
