### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by faridosc** [abourget/shuttle-go#4]
I get this error when doing `go get -v github.com/abourget/shuttle-go`:

```
github.com/abourget/shuttle-go
# github.com/abourget/shuttle-go
../../go/src/github.com/abourget/shuttle-go/osc.go:13:8: server.Handle undefined (type *osc.Server has no field or method Handle)
```

I am on archlinux.

**Comment by faridosc** [comment]
The issue seems to be related to this commit in go-osc:

https://github.com/hypebeast/go-osc/commit/edff003c8de14fd0897d4c881c1683b88b01729f

**Comment by abourget** [comment]
Closing as PR #5 should have updated all of this :) thanks for reporting!
